# Generated by Django 4.1 on 2022-09-30 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pessoa', models.CharField(default='Nome pessoa', max_length=500)),
                ('cpf', models.CharField(default='Cpf', max_length=11)),
                ('descricao_pessoa', models.CharField(default='Breve descricao para o site', max_length=500)),
                ('cargo', models.CharField(default='Cargo', max_length=50)),
                ('email_pessoa', models.EmailField(max_length=50, verbose_name='email')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao_produto', models.CharField(default='Breve descricao produto', max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=5)),
                ('estoque', models.IntegerField(verbose_name='quantidade em estoque')),
            ],
        ),
        migrations.CreateModel(
            name='Servicos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_servico', models.CharField(max_length=15)),
                ('descricao_servicos', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_post', models.CharField(default='Título', max_length=100)),
                ('resume_post', models.CharField(default='resumo', max_length=100)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
