# Generated by Django 4.1 on 2022-10-01 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='email_pessoa',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='pessoa',
            name='descricao_pessoa',
        ),
        migrations.AddField(
            model_name='blog',
            name='created_post',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='text_post',
            field=models.CharField(default='Texto', max_length=500),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pessoa',
            field=models.CharField(default='Nome', max_length=500),
        ),
    ]
