# Generated by Django 4.1 on 2022-10-02 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_email_pessoa_pessoa_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_usuario', models.CharField(max_length=25)),
                ('mensagem', models.CharField(max_length=100)),
                ('email_usuario', models.EmailField(max_length=50, verbose_name='e-mail')),
                ('createdFaleconosco', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
