# Generated by Django 4.1 on 2022-10-11 00:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cargo',
            field=models.CharField(default='Cargo', max_length=50, verbose_name='cargo'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cpf',
            field=models.CharField(default='Cpf', max_length=11, verbose_name='cpf'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='nome_pessoa',
            field=models.CharField(default='Nome', max_length=500, verbose_name='nome_pessoa'),
        ),
    ]
